from fpdf import FPDF
from typing import Dict
import logging

logger = logging.getLogger(__name__)

class RCAPDFGenerator:
    def __init__(self, output_path: str = "data/processed/rca_reports/"):
        self.output_path = output_path

    def generate(self, report_id: str, content: str) -> str:
        """
        Generates a formatted PDF report from LLM output.
        
        Args:
            report_id (str): Unique ID for the incident (e.g., TICKET-1001).
            content (str): The structured text generated by Groq.
            
        Returns:
            str: Path to the generated PDF file.
        """
        try:
            pdf = FPDF()
            pdf.add_page()

            #Header
            pdf.set_font('Arial', 'B', 16)
            pdf.cell(0, 10, f"Network Incident Root Cause Analysis: {report_id}", ln=True, align='C')
            pdf.ln(10)

            # Body
            pdf.set_font('Arial', size=12)
            # Multi-cell handles line breaks automatically
            pdf.multi_cell(0, 10, content)

            file_name = f"{self.output_path}{report_id}_RCA.pdf"
            pdf.output(file_name)
            logger.info(f"Succefully generated RCA PDF at {file_name}")
            return file_name
        except Exception as e:
            logger.error(f"PDF Generation Failed: {str(e)}")
            raise